# Site settings
title: Alice Spruit
email: alicespruit@hotmail.com
description: > # this means to ignore newlines until "baseurl:"

baseurl: ""
url: "/"
twitter_username: alicespruit 
github_username: bravebox

# Build settings
markdown: kramdown

exclude: ['_build', '_compass', 'config.rb']