# Site settings
title: Alice Spruit
email: alicespruit@hotmail.com
description: > # this means to ignore newlines until "baseurl:"

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.alicespruit.nl" # the base hostname & protocol for your site
twitter_username: alicespruit 
github_username: bravebox

# Build settings
markdown: kramdown
